package parser.kobobooks;

public enum KoboCategories {
    BIOGRAPHY_AND_MEMOIR,
    BUSINESS_AND_FINANCE,
    COMICS_AND_GRAPHIC_NOVELS,
    FICTION_AND_LITERATURE,
    FICTION_YA,
    KIDS,
    MYSTERY_AND_SUSPENSE,
    NONFICTION,
    ROMANCE,
    SCIENCE_FICTION_AND_FANTASY
}
